[package]
name = "vstrdbg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
rmp-serde = "1.1.1"
serde = "1.0.160"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
vstr = { version = "0.1.0", path = "../vstr" }
